/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\armleft.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Armleft(props) {
  const { nodes, materials } = useGLTF('/armleft.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube034_Cube039.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube001.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube002.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube003.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube004.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube005.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube006.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube007.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube008.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube009.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube010.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube011.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube012.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube013.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube014.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube015.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube016.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Cube034_Cube017.geometry} material={materials['None.001']} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
    </group>
  )
}

useGLTF.preload('/armleft.gltf')
