/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\body.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Body(props) {
  const { nodes, materials } = useGLTF('/body.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube009_Cube010.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube010_Cube011.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube011_Cube012.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube012_Cube013.geometry} material={materials['None.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Foot_LP.geometry} material={materials['Default_OBJ.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/body.gltf')
