/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\set_origin_armright.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Armright(props) {
  const { nodes, materials } = useGLTF('/set_origin_armright.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube034_Cube039.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube001.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube002.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube003.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube004.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube005.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube006.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube007.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube008.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube009.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube010.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube011.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube012.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube013.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube014.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube015.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube016.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube034_Cube017.geometry} material={materials['None.001']} position={[-0.005, -0.001, 0.003]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/set_origin_armright.gltf')
